### ISSUE TITLE
Need easy way to exclude an article from TOC listing

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#100]
Want to include an article in the flow, but have it hidden from the listing (e.g. ads, or maybe even the TOC itself)

**Comment by bramstein** [comment]
Since the TOC is completely microdata based it would make sense to exclude an article in the same way as how we specify the index page itself (e.g. `itemprop="url self hidden"`.) The alternative is to add a normal `class="hidden"`, but I think that doesn't go well with the microdata.

**Comment by fortes** [comment]
The only weird thing here, and this is true of "self" as well, is that we're adding a property of class hidden with the same value as the url, and just checking for the existence of the property.

The original reason behind self was because it was part of a rel/rev relationship, which is how those semantics work.

Solutions:
- `itemprop="url hidden"`: We're already overloading this anyway, so why not continue?
- `class="hidden"`: May have styling reprecussions
- `data-hidden`: Value-less attribute on item (at itemscope level)

I guess the larger question here is: How do we want to specify boolean properties in Microdata? Today we have `self` and `hidden` -- might need others later on.

**Comment by bramstein** [comment]
I gave this some thought, but haven't really reached a conclusion yet---all options are suboptimal. The boolean properties apply to the microdata so ideally they should be specified in microdata syntax. It isn't pretty though, I was already uncomfortable with having the `self` property there. Internally these boolean properties create copies of the itemValue they are defined on. So `<a href="htttp://www.example.org/" itemprop="url self hidden">example</a>` would create three properties with value `http://www.example.org/`, while we are only interested in whether the property names (`self`, `hidden`) are present.

Adding a class is out of the question for me, I think the styling repercussions are too great. `data-hidden` might work, but I wonder how it generalizes:
    <a href="http://www.example.org/" itemprop="url" data-hidden data-index>example</a>

**Comment by fortes** [comment]
If we do use `data-` attributes, perhaps it should be on the `itemscope` root? That way you don't have to check all the nodes for the attribute, just the root note.

I'm also fine with `itemprop=url self hidden` if need be. It's not pretty, but does keep everything in microdata. Fundamentally, the microdata spec doesn't really cover boolean properties.

I'll let you make the call here.

**Comment by bramstein** [comment]
I decided to go with a new data-\* attribute on the itemscope element. The attribute is called data-properties and contains boolean flags that affect the microdata item, but are not actually part of the microdata. I moved `self` into this new property and added a `hidden` flag which is used by the TOC to exclude an entry from the visible TOC. This leaves the design open for future flags. Changes are committed per SHA: 411fc7daebfd7b53d78d678396c3c3ec0a42b235

I'm open for suggestions on more appropriate flag names (not a big fan of `self`, perhaps `index`?) and perhaps also the data attribute name.

**Comment by fortes** [comment]
Agreed that `self` doesn't make too much sense. Perhaps `toc`?

Given the fact that this information (including `self`) should be within the `link rel=resources` -- perhaps we could remove the flag altogether?

**Comment by scottkellum** [comment]
Should this be closed? This works fine:
<code>data-properties="hidden"</code>

**Comment by bramstein** [comment]
It is implemented, but the ticket is still open because I'm not quite certain it is the nicest way to do it.

**Comment by fortes** [comment]
What if we use custom attributes as booleans? I.e.

```
<a href="..." data-hidden>
```

Or similar

**Comment by mixman** [comment]
How would one go about the opposite, that is, having an ad in the toc (sidebar) while not being part of the article flow?

**Comment by scottkellum** [comment]
@mixman Just don't supply grids for the particular ad and Treesaver should ignore it. The Treesaver Google Group is a good place for questions like these: http://groups.google.com/group/treesaverjs?pli=1

**Comment by 8wgremlin** [comment]
I can't seem to get the data-properties="hidden" to work, where am I meant to put it?

I've been doing this 
&lt;div class=&quot;keeptogether&quot; itemscope data-properties=&quot;hidden&quot;&gt;
&lt;div&gt;
&lt;h5 itemprop=&quot;title&quot;&gt;
&lt;a itemprop=&quot;url&quot; title=&quot;Great Britain&quot; href=&quot;Great Britain.htm&quot;&gt;Great Britain&lt;/a&gt;
&lt;/h5&gt;
&lt;p itemprop=&quot;deck&quot;&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;

is that rigth, cus it doesn't seem to work for me

**Comment by bramstein** [comment]
@8wgremlin That looks correct. Are you using an official release or the code from the repository?

**Comment by 8wgremlin** [comment]
@bramstein thanks.

I am using the original 0.9.1 code from a few months back. I got it working in the end, i had to add in the class="hidden".
I have to say the walk through needs updating because I can't seem to get the new 0.9.2 version to work

**Comment by bramstein** [comment]
This has changed now with the latest code in the repository. You can now use any boolean property in the `index.json` file to hide a TOC entry. For example if your index.json contains an entry with:

```
  {
    "url": "cover.html",
    "hidden": true
  }
```

You can do a conditional test in your TOC template to hide it:

```
   <div data-template="index">
       {{#children}}
         {{^hidden}}
           Any entry without the hidden flag, or with the hidden flag set to true will be ignored.
         {{/hidden}}
       {{/children}}
   </div>
```

The `hidden` property is just an example, you can use any property you like. See `test/functional/simple` for a demo. I'll add an example for this later.
