### ISSUE TITLE
IE8/IE7 partial binding clearing contents of class property

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#101]
Just spotted in IE8 for ICIJ:

<a data-bind="className:class" class="url {{ className }}" />

In other browsers, class="url xxx". In IE8, class="xxx"

**Comment by bramstein** [comment]
Fixed per SHA: 1d838342eca2503956fffad03f29ab97d1e1e3c7

**Comment by bramstein** [comment]
I added a test case for this. It seems the test case works fine in IE8, but acts strange in IE7, where it returns:

```
 <a class="url {{className}}" data-bind="className:class" class="test">Hello World</a>
```

I think the template code probably needs some special handling for the class attribute. Is this urgent?

**Comment by fortes** [comment]
Fixed the issue in both IEs, thanks!
