### ISSUE TITLE
Lightbox-specific content

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#105]
Figure payload specifically for lightboxes. Would allow for a video or other content that only plays within a lightbox.

Will need to change how event handling works, though.

**Comment by scottkellum** [comment]
What the figure code might look like:

<pre><code>
&lt;figure class="zoomable"&gt;
       &lt;div class="no-lightbox" data-size="videoimg"&gt;
               &lt;img src="img.jpg" /&gt;
       &lt;/div&gt;
       &lt;div class="lightbox" data-size="video"&gt;
               &lt;object&gt;Youtube Video&lt;/object&gt;
       &lt;/div&gt;
&lt;/figure&gt;
</code></pre>

**Comment by Sampathmattapalli** [comment]
Hi scottkellum,
I was tried above your solution about video playing but it's not working.

Let me know if am making anything wrong.

Thanx !
Sam
