### ISSUE TITLE
Strange layout/errors when same article is in the TOC twice in a row

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#106]
Can replicate in simple functional test if you make two entries for index.html

**Comment by bramstein** [comment]
I see the problem. What would you expect to happen when an article is in the TOC twice? Should the microdata be combined into one entry if the two TOC entries are the same? If so, what happens to the title and any other microdata that might be different. I need to think about this one a bit more.

**Comment by fortes** [comment]
I think we allow the article to be in there twice, and treat them as separate entities.

This happens in the newsdemo, since a story could be in both "Top Stories" and "World" -- this works for the most part today, it just seems we have a bug when they are adjacent.

ArticleManager has some code to deal with the article index in cases where the article appears more than once.

**Comment by bramstein** [comment]
I had a look at the case where two identical articles are adjacent: it seems the problem is caused by the `populatePages` method in `chrome.js`, which checks if a page node is already inserted into the DOM, and skips it if it is. I think the best solution is to clone the node in the `ArticleManager.getPages` method, but I have to do some work to see if this is safe to do.

**Comment by fortes** [comment]
Ah, that makes sense. Top concern here will be memory leaks -- don't want to have a bunch of clones of the node floating around -- likewise, `page.deactivate()` is there to lose any reference, etc.

A possible simpler fix: Don't allow the same article twice in a row in the TOC -- collapse them into one entry. 

Issue: Imagine: A B A -- each are 1-page articles, would still have page 1 of A repeated even though they are not adjacent. Collapsing adjacent duplicates may still be a good idea, but won't fix the issue completely.

**Comment by bramstein** [comment]
You probably know the code better than me, but wouldn't creating a clone of the whole page object when this situation is detected solve the problem? Instead of referring to the same page object, each logical page would get its own instance. The instances will then be destroyed as usual.

**Comment by fortes** [comment]
Should be fine. Thinking it over, even making more than one DOM node shouldn't be a bit issue either.

**Comment by bramstein** [comment]
Fixed per SHA: 73db4109bbce2fb8530c94c1ae7beb0b7474012f
