### ISSUE TITLE
Client side hyphenation

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#107]
Consider doing client side hyphenation, so that authors no longer need to sprinkle `&shy;` over their articles (see realeats content.)

**Comment by fortes** [comment]
Create plugin/detect presence of Hyphenator.js ( http://code.google.com/p/hyphenator/wiki/en_PublicAPI )

**Comment by bramstein** [comment]
My fork of Treesaver now contains hyphenation support: https://github.com/bramstein/treesaver/tree/hyphenation (see the test/functional/alice example.) It needs some better testing and configurability, but the basics are there. It uses my hyphenation library "Hypher" (https://github.com/bramstein/Hypher) which should be faster and smaller than Hyphenator.js (and seemingly also more correct---but I'm not sure about that one yet.)
