### ISSUE TITLE
Page turn animation jerks initially after swipe

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#112]
Need to change the animation duration? Or calculate velocity/momentum?

**Comment by scottkellum** [comment]
Seems to be fine in 0.9.2 Closed?

**Comment by fortes** [comment]
The code here is wrong, it needs to disable CSS transitions while swiping.

**Comment by fortes** [comment]
Fixed by SHA: 859cf7601c5ca7e05775f692f681020a6f907873 and others
