### ISSUE TITLE
Scrolling content sometimes scrolls in wrong direction

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#118]
The side bar started moving horizontally instead of sticking to a strictly vertically scrolling pane. I am having trouble replicating it myself but it has happened twice in the iPhone simulator.

**Comment by fortes** [comment]
Probably happening because there is space to scroll horizontally. Is the content of the sidebar the same width as the sidebar?

**Comment by scottkellum** [comment]
content in the side bar is the same width as the side bar. Maybe in some instances a change in state will push something over the edge. Still attempting to replicate and isolate the occurrence. It happens in the iPhone sim.

**Comment by scottkellum** [comment]
Haven't seen or head of this bug in a while, going ahead and closing it.
