### ISSUE TITLE
Web OS support

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#120]
- side bar not hiding properly.
- mobile templates not being loaded.
- keep nav above native nav.

**Comment by fortes** [comment]
Do you have a test device? Or just using the emulator?

Not sure how to keep UI elements above their native UI ...

**Comment by scottkellum** [comment]
On Rogers old pre, witch is now part of the device lab. Keeping ui elements above the fold is last on the priority list because you can scroll down easily enough
