### ISSUE TITLE
jittery page swipes iOS 4.2

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#121]
When swiping slowly on the iPad the page jitters back and forth quickly during the swipe.

**Comment by andreieftimie** [comment]
Also confirmed on the iPhone on 4.2

**Comment by scottkellum** [comment]
Really bad on an actual divice, should be moved to a high priority. Seems fine in the simulator.

**Comment by scottkellum** [comment]
Could be a conflict between where the JS says the page is and the CSS transition says the page is. A possible fix is to disable CSS transitons when the a touch point is active, once the user is done swiping the transition can start from that point.

**Comment by fortes** [comment]
This was an issue with CSS transitions, now fixed in SHA: e817c3e670a33e4f1455bb6082b37bf491789e24 and others
