### ISSUE TITLE
Rewrite the module system

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#122]
Rewrite the module system so that code can refer to its own module name or its dependencies by their module name. The build system would then be responsible for defining the actual file names at build time.

This would solve the following two problems:
- Code referring to filenames.
- Module names which cannot contain version numbers (due to the Closure compiler limitation on module names.)

**Comment by fortes** [comment]
When you do this, also rename `ui.js` to `treesaver-ui.js` to avoid any potential confusion.

**Comment by bramstein** [comment]
Fixed per SHA: 007cb1314015295b9d84d1382b0d095ad26f432a

I also renamed ui.js to treesaver-ui.js per your request. Modules are still specified in modules.json, but the syntax is slightly different. Rerun "paver" after checking out the commit.
