### ISSUE TITLE
TOC Sections

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#123]
Ability to have some hierarchy in the TOC in order to provide sections for stories (as in AP demo).

Needs some design thinking.

**Comment by bramstein** [comment]
Why not simply allow nesting microdata items?
      <div itemscope>
        <h1 itemprop="title">Section title</h1>
        <div itemscope>
          <h2 itemprop="title"><a itemprop="url" href="one.html">Article One</a></h2>
          <p itemprop="abstract">Lorem ipsum...</p>
        </div>
        <div itemscope>
          <h2 itemprop="title"><a itemprop="url" href="two.html">Article Two</a></h2>
          <p itemprop="abstract">Lorem ipsum dolor sit amet...</p>
        </div>
      </div>
We can use non top-level microdata items that are also leaf nodes as TOC entries while the other levels define sections.

This will require some small changes to the TOC template:
      <div data-bind="toc">
        <div data-bind="section">
          <h2 data-bind="title">Section title</h2>
          <div data-bind="article">
            <h3><a data-bind="url:href title">Article Title</a></h3>
            <p data-bind="abstract"></p>
          </div>
        </div>
      </div>

There may be a problem when the number of nested sections in the TOC doesn't match the template, but that could be solved by picking only the lowest matching levels.

**Comment by scottkellum** [comment]
Does this work? It is needed.

**Comment by bramstein** [comment]
It does not currently work. Filipe and I have been discussing how to implement this, but there is no implementation yet.

**Comment by bramstein** [comment]
This is in the repository now. Have a look at the `examples/(nested|table of contents|singlefile)` for working demos. The new templating syntax can be found in the `test/functional/simple` demo. Documentation will be forthcoming shortly.
