### ISSUE TITLE
Progress bar for reading

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#128]
Instead of page numbers? Or perhaps as indication of articles remaining?

**Comment by bramstein** [comment]
I was thinking along the lines of the progress bar on a Kindle, where you can see both your progress and the beginning and end of sections (chapters, articles, etc.) I wouldn't replace page numbers, but complement them, especially for long magazines or books.

**Comment by fortes** [comment]
Agree about not replacing for all, but do want to give an option for authors.

Similarly, many iPhone apps use a small circle per page, with the current page as a darker circle.

**Comment by scottkellum** [comment]
Had this in issue #130 (now closed)

What is needed to make it work now:
- Article and issue length (in % for width)
- % of article read (div inside of article, with a % width) - Flag an article as read - allow multiple <code>data-bind="toc"</code> flags.
