### ISSUE TITLE
Allow "scroll" flag to scroll horizontally

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#131]
Attempting a horizontal scroll for the ToC in the chrome redesign but running into problems. I assumed running all the items inline with "white-space: nowrap" css attribute. Doesn't seem to be working though.

**Comment by fortes** [comment]
Scroll supports horizontal already, make sure you have content that is actually wider than the scroll container.

**Comment by scottkellum** [comment]
overflow hidden:
http://scottkellum.com/temp/overflow-hidden.png

overflow visible:
http://scottkellum.com/temp/overflow-visable.png

Working copy is in Dropbox/treesaver/tsvr-projects/where
