### ISSUE TITLE
Images dropping from photostories

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#137]
Images just dont show in photostories at some screen sizes. The grids are simple with sizetocontainer flags.

Can be replicated in Read Eats. The bug even shows up on the socializer video... I can't seem to fix it on my end...

**Comment by fortes** [comment]
Need more detail -- do you have a copy of this bug in action?

**Comment by scottkellum** [comment]
http://www.youtube.com/watch?v=rctiAtD6KKs
at 8:08, no vertical images...

**Comment by fortes** [comment]
I believe this was due to incorrect min height calculations, correct? Closing. (In the future, nomad specific bugs should go into their issue tracker)
