### ISSUE TITLE
Support flags from articles to templates

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#138]
Translate something like this:
[article data-grids="feature" data-flags="green rounded"]

to something like this:
[div class="grid feature green rounded"]

This way I can use the same grid but change things like the colors

**Comment by scottkellum** [comment]
Nicely done. I have been using a work around for a little while now where flags can be written from the data in the toc.json file.

grid:

``` html
<div class="grid department">
      <div data-ts-template="document"><div class="type {{type}}">
        ... content...
      </div></div>
</div>
```

toc:

``` js
"url": "article.html",
"title": "title",
"type": "green rounded"
```

It ends up being a little verbose but powerful. I will discuss this with out JS devs and see how to merge.

**Comment by bramstein** [comment]
Thanks, this is now merged in!
