### ISSUE TITLE
Photo act in Real Eats not loading

### ISSUE THREAD

**Issue by goldmatt** [Treesaver/treesaver#140]
The Chocolate story in the last issue won't load. Have had one complaint and experienced it myself.

**Comment by fortes** [comment]
Matt, can you file this in the Nomad repository instead? I'd like to use this only for tracking Treesaver.js issues (i.e. issues we know related to Treesaver -- this case we have to investigate and see if it's Xierpa or the Grids or whatever first)

**Comment by goldmatt** [comment]
OK. I can close it out.
