### ISSUE TITLE
allow more microdata to be pulled into URL sharing

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#142]
Currently the mailto link looks like this:
mailto:?subject=I would like to share this article with you.&body={{current-url}} ...

It would be nice to send something like this:
mailto:?subject=I read this great article in {{vertical}}, {{title}}. I hope you enjoy it too. &body={{current-url}} ...

**Comment by bramstein** [comment]
This should be very easy now with the most recent changes to the TOC and index. Which fields do you need?

**Comment by scottkellum** [comment]
Oh nice! Are the fields flexible or do you need a list? I imagine they will change dramatically in different use cases, the above being one use case.

**Comment by bramstein** [comment]
Flexible in theory. Right now the following fields are available, and hard-coded:
- pagenumber
- pagecount
- url
- documentnumber
- documentcount

I could add `currentdocument` which would give you access to all meta-data defined in the index.json file (so you can add any field and have it available.)

**Comment by scottkellum** [comment]
<code>articletitle</code> and <code>publicationtitle</code> would be the most useful. <code>articletitle</code> being a human readable name assigned to an article and <code>publicationtitle</code> being a human readable name assigned to the publication. If you can think of a more generic name for the publication/edition/issue... lets use that.

Looking forward, people may want to include date, time, issue #, location, article subtitle, article description, issue theme, and publisher name...

**Comment by bramstein** [comment]
I've added an example of using the document title:

https://github.com/Treesaver/treesaver/blob/master/examples/template-position/resources.html

Which is automatically retrieved from the index.json:

https://github.com/Treesaver/treesaver/blob/master/examples/template-position/toc.json

You can put any field in there (with whatever name you wish) and have it accessible through `currentdocument`. So for example in your index.json you would have:

```
{
   "url": "article1.html",
   "title": "Article One",
   "subtitle": "The very first article",
   "time": "2011-06-14"
}
```

And you can access it in any template with:

```
<div data-template="position">
   {{#currentdocument}}
      The article title is: {{title}}, the subtitle is: {{subtitle}} and it was published at {{time}}.
   {{/currentdocument}}
</div>
```

Anything with `data-template="position"` will be updated every time a page is changed. Be aware that Mustache.js (the templating engine) does not support encoding URL components, so we either need to put encoded values in the index.json or find some other solution.

**Comment by bramstein** [comment]
We could pull `title` into the top level so you don't need to wrap it into `currentdocument`. The only problem I see with it is that it gives special meaning to title, whereas before it was just a field (maybe it is special anyway, because it falls back to the HTML `<title>` element.) Need to think about it for a bit. I've also been playing with introducing a `currentdocument` template, so it is not part of the `position` template any longer. This would allow us to rewrite the template as:

```
<div data-template="currentdocument">
  The article title is: {{title}}, the subtitle is: {{subtitle}} and it was published at {{time}}.
</div>
```

Which I guess would also solve your problem (and the general case.) What do you think?

**Comment by scottkellum** [comment]
Sounds good, I think you have it figured out, just need to make it simple and accessible.

**Comment by bramstein** [comment]
The `currentdocument` template code is in the repository now. I've changed the example accordingly. I'm thinking about replacing Mustache.js with Handlebars.js so we can hook up custom encoding functions for cases where you do template expansion in attributes/URLs.

**Comment by scottkellum** [comment]
fixed with new toc format.
