### ISSUE TITLE
Sidebar should roll away on selection

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#145]
After you select where you want to go the sidebar should become inactive.

**Comment by bramstein** [comment]
You should probably use a menu for cases where you want the box to close when an item is selected. With the most recent changes you can use multiple sidebars and menus, so you can style a menu like a sidebar and achieve that behaviour.

Menu and sidebar are a bit awkward names, it is better to think of them as a container that closes when a mouse is clicked anywhere (menu) and a container that is closed when a mouse is clicked anywhere but the container or other containers of the same type (sidebar.) Perhaps we should come up with better names, any suggestions?

**Comment by fortes** [comment]
Will need to support scrolling/swiping on these menu/sidebar hybrids as well. Will need to think about this design.

**Comment by andreacampi** [comment]
Sorry about the multiple pushes, I made a mess while rebasing :)

Bram:

> Menu and sidebar are a bit awkward names, it is better to think of them as a container that closes when a mouse is
> clicked anywhere (menu) and a container that is closed when a mouse is clicked anywhere but the container or other
> containers of the same type (sidebar.)

I agree with the general principle; still, sidebars scroll and menus don't, so in general they are what people want.
Having the option of closing the sidebar automatically on click is really neat.

**Comment by andreacampi** [comment]
Pull request is #280

**Comment by andreacampi** [comment]
An implementation of this has been merged a while back.
