### ISSUE TITLE
Chrome: Selected pages produce flicker

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#148]
See: http://news.ycombinator.com/item?id=2188160 I have been able to reproduce this on Ubuntu using Chrome 9.0.5 from the beta channel. I can't reproduce this on Chrome 8.0.5, Ubuntu though. The page transition animations also seem to be broken, perhaps these two issues are related.

**Comment by fortes** [comment]
I think this may be due to the fact that the Tuna demo is running on an old build of Treesaver. Need to investigate though.

**Comment by bramstein** [comment]
This problem seems to have disappeared with newer Treesaver versions. I can no longer reproduce it.
