### ISSUE TITLE
Possible to use History.js for graceful degradation of HTML5 History API?

### ISSUE THREAD

**Issue by balupton** [Treesaver/treesaver#151]
Hey Filipe,

Just watched the Scrobilzer interview of you guys and awesome stuff! You guys are really on the ball with this, and you have a great personality for interviews. I'm the author of the other [History.js](https://github.com/balupton/History.js) project and I'm wondering if there is anyway we can work together?

History.js benefits if it were to be included appear to be:
- cleaner urls for HTML4 browsers
- continued support for state data and title in HTML4 browsers
- dedicated team behind History.js to ensure it works perfectly

I'd be happy to add in the change myself, as well as make sure that History.js fits your needs :)

Love to hear from you,
- Benjamin Lupton (skype balupton) (email contact@balupton.com)

**Comment by fortes** [comment]
Hi Benjamin, thanks for getting in touch.

If you look at `src/lib/history.js` you'll see we have a history implementation that works for older browsers that is based on [fortes/history.js](https://github.com/fortes/history.js) -- in theory it's working fine, but I'm open to hearing out reasons for the switch. I'll send you email.
