### ISSUE TITLE
Trsvr crashing Moto Artix 4g browser

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#165]
Everything seems to load fine until it is about to render the page. Then the browser crashes.

Could be any number of things, may be solved with a software update later. (2.2.x versions of Android are known to be flaky on Tegra2). Tested with all Nomad verticals on the Atrix 4g. Completely stock.

**Comment by fortes** [comment]
Is there a simulator anywhere? A device I can test with?

**Comment by scottkellum** [comment]
David at Nomad has one. It's a modified Android 2.2.1 browser, no simulator other than Googles.
