### ISSUE TITLE
Bug with fixed and bottom containers

### ISSUE THREAD

**Issue by Jax1961** [Treesaver/treesaver#166]
When a container is fixed, the function treesaver.layout.Page.fillContainer returns before honouring the 'bottom' class (i.e. setting 'top' or 'bottom' to 'auto').

Moving the lines

```
// If the container is fixed, then we are done no matter what
if (!map.flexible) {
  return true;
}
```

after the code which looks for the 'bottom' class seems to fix the problem, but I'm not sure of any side-effects this might have.

**Comment by Jax1961** [comment]
I should learn 'Markdown', really! ;)

**Comment by fortes** [comment]
The idea is that a fixed container gets no adjustment from Treesaver -- it is left as is by whatever absolute positioning is used.

[Did you purposefully close this bug when you commented?]

**Comment by Jax1961** [comment]
I see. So I should explicitly set top or bottom to 'auto' in my own CSS, then, I guess?

No, I didn't purposefully closed the bug. 'Twas a noob error!

**Comment by fortes** [comment]
If you want a fixed container to stay on the bottom, I'd recommend using something like:

```
bottom: 10px;  /* Or however far you want it from the bottom edge */
height: 100px; /* i.e. however tall you want it to be */
```

Let me know if that doesn't work for you.
