### ISSUE TITLE
getTOCLocation should autodetect when contents is self

### ISSUE THREAD

**Issue by andreacampi** [Treesaver/treesaver#167]
treesaver.ui.ArticleManager.getTOCLocation relies on rel="self" to detect that "contents" is the same as the current page.

However, that gets in the way of e.g. having a single Server-Side Include file with the parts of <head> that are common across all pages of a publication.

I have been running with this change with no ill effects:

```
  if (!link || link.getAttribute('rel').indexOf('self') !== -1 || treesaver.network.absoluteURL(link.href) == treesaver.ui.ArticleManager.initialUrl) {
```

I am going to send a pull request after I run tests, but I thought I'd gather feedback first. So, what do you think?

**Comment by fortes** [comment]
This works, although `rel=self` will still be recommended since URL matching can be brittle (i.e. `/` vs `/index.html`).

But I don't think there's much risk in adding this check just in case.

**Comment by andreacampi** [comment]
Sure, indeed. It's good to have both options, that's all :)

**Comment by bramstein** [comment]
This has been added per SHA: 8dccfe787ccd2ab639d8573d84026c45dbf0ee15

Thanks a lot for the fix!
