### ISSUE TITLE
Chromium v12: use strict / delete unqualified identifier

### ISSUE THREAD

**Issue by mattkeenan** [Treesaver/treesaver#168]
Chromium 12 has stricter compliance with ECMA script, it complains about deleting objects that aren't fully qualified (scoped). There are two such deletes in 0.9.1;

delete xe; delete ze;

both of these are on line 122

**Comment by fortes** [comment]
Thanks for checking this. Firefox 4 does the same.

Fixed in SHA: 26010ac4298b4f33e3039715f0e915fb5b6dea29

**Comment by mattkeenan** [comment]
That was exactly the fix I used locally...

**Comment by fortes** [comment]
Yeah, closure compiler is flattening the variables and causing those stray deletes. I need to figure out how to fix that and then re-enable strict mode.

**Comment by bramstein** [comment]
I guess in this particular case there would be no harm it just setting those flags to false (boot.js/cleanup_)
