### ISSUE TITLE
iPad swiping!!!

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#17]
iPad swiping still not fixed! This is what most people are complaining about.

**Comment by fortes** [comment]
Got any detail here? Is it every time? On certain pages? Etc.

**Comment by scottkellum** [comment]
It is inconsistant. It seems to only happen on the iPad, no reports on iPhone.

It can be reproduced by swiping too fast (possibly in the middle of an animation?) and can be easily reproduced if you swipe back and forth a few times fast. The arrows also seem to be disabled in this state.

**Comment by scottkellum** [comment]
Seems to be plaguing android 2.2 devices (our EVO owners are getting cranky)

**Comment by fortes** [comment]
Committed partial fix, need more investigation around other iPad quirks: SHA: 6afcac63fd0a932802e044cfd1b32c8e4cf89f58

**Comment by scottkellum** [comment]
Works better, Managed to get it stuck but now it gets un-stuck just by swiping through.

**Comment by fortes** [comment]
localStorage can throw quota errors on iPad, protect against the uncaught exception. Closed by 5ed7931b1ea1090a8ed86c88606a1ebe01d1f609

**Comment by scottkellum** [comment]
Smooooth. works perfectly and can't get it to freeze :)
