### ISSUE TITLE
Expose functionality for font size changes

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#170]
We should expose functionality to the chrome that allows the user to change the font size. This way, we can automatically do a relayout.

**Comment by fortes** [comment]
I was thinking perhaps we should use CSS transforms to scale the page completely.

For example, if we have an 800x600 screen and we zoom to 200%, we perform layout as if we were at 400x300 and then apply a 200% scale transform on the result. That will give the effect of changing the font size without requiring re-measuring all of the text (and therefore should be quite fast).

My only concern here is with browser bugs that may occur with applying the scale transform.
