### ISSUE TITLE
Simplify build process

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#174]
Needless complexity right now. Some first steps:
- Include `deps.py` so people don't have to run it on first try (or even at all in most cases?)
- Include `base.js` from Closure Library. No need to pull down entire SVN repo just for one file
- Include `compiler.jar` from Closure Compiler. Keeps everyone on same compiler version, minimizes dependencies.

May also wish to consider moving from Paver to Rake someday.

**Comment by bramstein** [comment]
Done per SHA: 7e655ae92d553c22639bc78c848509de039ff9c1

We might want to write down a roadmap at some point as well.
