### ISSUE TITLE
Consider not extending native prototypes

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#175]
See: http://www.sencha.com/forum/showthread.php?123448-Sencha-Touch-ExtJS-and-Treesaver-problem

As much as I like extending native prototypes, perhaps it is not in our interest as it might break with other frameworks that do not expect/guard against it.

**Comment by fortes** [comment]
At the very least, we should be testing for existence of Array.prototype.remove before we clobber it.

**Comment by bramstein** [comment]
I cleaned up the code that extends native prototypes a bit per SHA: e4ee2e9eab9b013f23d4137cdfc1130cfd63b6a5

Treesaver now only extends native prototypes if the function is a standard one (i.e. forEach, indexOf, etc.) Any function that is not standard has now been moved into the treesaver.<type> namespace. It might not solve the immediate problem, but it is a start.

**Comment by bramstein** [comment]
After thinking a bit more about this, I'm satisfied with the current solution. Frameworks should expect that other frameworks may wish to supply standard JavaScript functionality if it is not natively available. With the above fix, Treesaver does not extend the Array or Object prototype except to add well known functions such as forEach, every, map, etc.

**Comment by fortes** [comment]
I agree that the polyfill model is the way to go. We should patch in for native functions when they don't exist (`forEach`, `map`, etc). This will make it simple to use the fast native functions.

Note that `Object.keys` and `Array.isArray` and a few others are part of JS 1.8 it seems.
