### ISSUE TITLE
Support more than one menu / sidebar in Chrome

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#177]
Something to consider.

**Comment by bramstein** [comment]
Added per SHA: f5a598de17cc614b87b575e16157286f7b7b1cb5 and SHA: e9dccae5ce7a4ed7697762b8317e89e2bc2de1d0

Also added are two examples of how to use multiple menus and sidebars. The syntax has not changed, the only difference is the position of the `sidebar-active` and `menu-active` classes. These are now set on the element with classes `sidebar` and `menu` respectively.
