### ISSUE TITLE
Support data-src style cloaking for iFrames and other elements

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#179]
Need to figure out which elements to support: `iframe`, `video`, `object`?

**Comment by umbiki** [comment]
And code can become something like this:
<code>
['img','iframe','video','object'].forEach(function(elemtype) {
     treesaver.dom.getElementsByProperty('data-src', null, elemtype, container).
        forEach(function(e) {
          e.setAttribute('src', e.getAttribute('data-src'));
      });
  });
</code>

**Comment by bramstein** [comment]
Perhaps `audio` as well?

**Comment by bramstein** [comment]
I've added `<audio>` and `<source>` to the list as well per SHA: 4bb41de9042cbc191341d6a8360cd7921ff27636. Closing the issue until further notice.
