### ISSUE TITLE
treesaver does not work for Chrome 12.0.712.0 using tutorial

### ISSUE THREAD

**Issue by stiller** [Treesaver/treesaver#181]
treesaver does not appear to do anything when viewing the tutorial content in Chrome.

**Comment by bramstein** [comment]
Seems to work in 11.x. I would prefer to wait for at least a beta before compatibility testing.

That said, are there any errors in the developer console?

**Comment by stiller** [comment]
Uncaught SyntaxError: Delete of an unqualified identifier in strict mode. treesaver-0.9.1.js:122

**Comment by bramstein** [comment]
Ah, that is a known error. Could you try Treesaver 0.9.2? It should fix that problem.

**Comment by bramstein** [comment]
Closing this until further notice.

**Comment by stiller** [comment]
It works fine with 0.9.2
