### ISSUE TITLE
Support vertical pagination

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#185]
In-article vertical paging, horizontal for between articles.

**Comment by speedmax** [comment]
Anyone wants this feature? 

I would like to work on this and it would be great if anyone can point me to the right direction.

**Comment by bramstein** [comment]
We'd be happy to take any patches, what do you need to get started? Have a look at `src/ui/chrome.js` to see how the current pagination/swiping is done.

**Comment by tpmurph** [comment]
I would love for this feature to be added to treesaver. I think it would really help navigation for my app

**Comment by scottkellum** [comment]
Flagged for deletion. This goes against the core ideology of Treesaver by breaking narrative. Unless a compelling argument can be given for keeping it.
