### ISSUE TITLE
Motorola Xoom Quirky

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#186]
Played with a device for 2 min, but the Xoom wasn't able to swap articles for some reason. Need to get the device or an emulator.

**Comment by scottkellum** [comment]
Emulator is in the new Android SDK. While the benchmarks appear good I have heard things about other "html5" projects having some issues with the XOOM...

**Comment by fortes** [comment]
The emulator is dog slow, ridiculous.
