### ISSUE TITLE
Better support for photo stories

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#194]
It is currently possible to create photo stories, but the syntax and layout are a bit awkward. Since this seems to be a common wish, it would be nice if we had support for "native" photo stories (with a simplified syntax.)

**Comment by fortes** [comment]
Agreed.

Generally, something I've wondered is if we should include some built-in templates for common scenarios (like full-page image, etc). Or perhaps this is just part of the boilerplate.

**Comment by saidimu** [comment]
Anything to lower the learning-curve would be helpful, especially for common scenarios.

Ease-of-use is arguably as important as feature-set, sometimes more so.

**Comment by scottkellum** [comment]
Would be nice to mix with the sizetocontainer flag. Currently the flag only scales vertically but if both the figure and grid scaled gracefully to the maximum size then there would be a significant reduction of grids and they would look better as well.

**Comment by pearsonfoundationbackup** [comment]
@bramstein, when you say the syntax is awkward - is there an example you can share?

**Comment by bramstein** [comment]
The syntax is currently very geared towards adaptive column layouts. To create a photo story that adapts to the screen size you'll have to define several image sizes that correspond each of the possible column layouts. It might be a good idea to create a specialized syntax for a photo story where the only content is an image and a caption and all the resizing is handled by Treesaver. Basically a fancy lightbox that is part of the article flow.

**Comment by pearsonfoundationbackup** [comment]
Thank you. We are using Treesaver to create a children's book reading app. Most book pages have only a large image, sound, notes and little if any text. So far, besides the fact Treesaver isn't really geared towards such an application, it's working out very well.

**Comment by bramstein** [comment]
We're quite open for suggestions on new syntax or better ways of doing
things. Is there anything that would make it easier to accomplish your
goals? We prefer seeing some real use-cases before deciding on
changing or adding features. It would be great if you could share some
of your thoughts on the subject.

Thanks,

Bram

On Tue, Jun 7, 2011 at 6:46 AM, PFoundation
reply@reply.github.com
wrote:
