### ISSUE TITLE
Safari 4 next page

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#20]
Only the first page loaded is displaid. Impossible to turn page and get past the cover. No loading graphic or next page preview.

**Comment by fortes** [comment]
All Treesaver, or a specific vertical/article?

**Comment by scottkellum** [comment]
All verticals running treesaver.

**Comment by fortes** [comment]
Should be closed by the same fix for the iPad swiping. Can you confirm?

**Comment by scottkellum** [comment]
Works in Safari 4. Just tested Safari 3 and fails to load pages. not sure how far back we are going.

**Comment by fortes** [comment]
Can you open a separate issue for Safari 3 compatibility? Thanks.
