### ISSUE TITLE
dots in stylesheets....

### ISSUE THREAD

**Issue by riesart** [Treesaver/treesaver#200]
Hi there everyone,

I think it's a good idea to put a space before dots when defining an extended class in the stylehseet.
It took almost 2 hours to figure out why the sidebar and the menu where not working....

NO: sidebar.close-sidebar
YES: sidebar .close-sidebar (mention the space before .close-sidebar)

Kind regards, 

Richard

**Comment by bramstein** [comment]
There have been some changes to the way menus and sidebars work recently, so that might explain this situation. Could you explain a bit more about what happened? Thanks!

**Comment by riesart** [comment]
Sometimes there are no spaces before dots in the definitions of the classes in the example-stylesheets. And it doesn't apply to the sidebar, but all declarations in the stylesheet;

.class.anotherclass
.class anotherclass

doesn't work: .classNOSPACE.anotherclass
works: class SPACE .anotherclass

I hope I explained it more clearly this way.

**Comment by riesart** [comment]
DOTclassNameDOTclassName

DOTclassNameSPACEDOTclassName

**Comment by bramstein** [comment]
I think the problem is that the examples in the repository are for the new menu and sidebar code. My guess is that you are using an older Treesaver release for which the CSS syntax is incorrect.

**Comment by riesart** [comment]
I am using the latest treesaver release. Anyway, I made changes to the stylesheet to get it working.
Thanks for replying and for the great treesaver framework!
