### ISSUE TITLE
Re-enable strict mode

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#212]
Need to make sure Closure Compiler works correctly though

**Comment by bramstein** [comment]
Seems it might be as simple as setting `--language_in ECMASCRIPT5_STRICT` in a recent version of closure compiler. We had a few specific cases where it would generate code that deleted local variables. These should be easy to check for.

**Comment by fortes** [comment]
Yup, just need to make sure their compilation doesn't create errors for us.

**Comment by bramstein** [comment]
I just had a go at this, and it seems to generate valid code after upgrading to the latest version of the closure compiler. All examples seem to run fine.

**Comment by bramstein** [comment]
Closing as it seems to function fine.

**Comment by fortes** [comment]
Hm, this seems to be causing problems in Firefox 5 -- there's some bad statement around a use of `in`. Removing `use strict` solves the issue.

Related: Closure compiler adds many `use strict` clauses to the file, which is weird.

**Comment by bramstein** [comment]
Damn, seemed to work fine in Firefox 4, Chrome 12 and Safari 5. Oh well, easy to take out.

**Comment by fortes** [comment]
The problem is with `goog.exportSymbol`, which is getting messed up by the way we are packaging the script. Let me take a shot at fixing the issue.

**Comment by fortes** [comment]
OK, SHA: bab6e8e8102d9d77d79ae5676c5df9d9fc80b9f5 fixes the issue w/ Firefox, so we should be better now.

However, it's still weird that all the `use strict` clauses get repeated. I'll open up a separate ticket though.
