### ISSUE TITLE
Honor target="..." on clicked links

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#214]
In case developers want links to open in new window. See mailing list here: https://groups.google.com/forum/#!topic/treesaverjs/TdEfV0B9wG8

**Comment by bramstein** [comment]
Done per SHA: c4b07539d54cc6126d2cba52d42c7ceb7d8f654c. Treesaver now respects `<a href="..." target="..."></a>` where `target` can be `_blank`, `_top`, and `_parent`.
