### ISSUE TITLE
Make <article> tag optional for Treesaver content

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#219]
In order to simplify markup, make the `<article>` tag optional. If there is none present, assume the entire contents of `<body>` are the article.

Using `<article>` allows for multiple stories in one file, as well as providing content for non-Treesaver browsers. However, many developers aren't using either feature, so we can simplify their markup.

**Comment by bramstein** [comment]
Good idea, I've done this per SHA: f9f64f1e7901ae1bcea559c6bb5a3e45fabed15f
