### ISSUE TITLE
Opera browser support

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#22]
javascript doesn't load in Opera. It shows the non-treesaver page.

Mark was also wondering about Wii support.

**Comment by fortes** [comment]
I've never used a Wii browser, would love to test though.

**Comment by scottkellum** [comment]
Maybe we can buy one to "test" for the office :)
We have a wii and PS3 at my old office we can probably do some testing on.

**Comment by bramstein** [comment]
Opera should now be working. Unfortunately, the Opera browser on the Wii doesn't load treesaver. I'll open a separate issue for that.
