### ISSUE TITLE
Support <meta> tags for article metadata

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#220]
Since we're removing Microdata support, we should add reading of `<meta>` tags for article metadata. For example:

``` html
  <meta name="abstract" content="This is the abstract">
```

Will add a bindable variable called `abstract` to the article. This is much more straightforward than dealing with `itemscope` and `itemprop`, although it does potentially cause some repetition.

**Comment by bramstein** [comment]
Done per SHA: 8ed0e71f1d84ccb31ee95d21bc21c0cc5b843029

All `<meta>` tags with a `name` and `content` attribute are now copied to the meta-data object for each document. This will overwrite any value that may have been previously specified in the index JSON file.
