### ISSUE TITLE
paver debug command generates treesaver.js that has mustache dependency

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#222]
Is there someway of bundling everything into a single standalone file for convenience?

**Comment by bramstein** [comment]
I actually fixed this but didn't commit. Will do so later tonight.
On Jul 27, 2011 7:19 PM, "fortes" <
reply@reply.github.com>
wrote:

**Comment by bramstein** [comment]
Fixed per SHA: af672cfa3ad704a2add22e935a710369f84677b2

The build/modules system is still a big hack. When we have some time we should redo it.

**Comment by fortes** [comment]
Agreed, I'm thinking we just go full-on JS and use Jake: https://github.com/mde/jake
