### ISSUE TITLE
Consider integrating / cloning has.js API

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#228]
Treads the same ground as the capabilities infrastructure: https://github.com/phiggins42/has.js

Things to think about:
- Make sure Closure Compiler can still strip away unnecessary code in specialized builds. (Related: https://github.com/joehewitt/hascan )
- Do we expose this API?

**Comment by bramstein** [comment]
I actually did something similar with Modernizr 2, which allows you to build a custom JS file so you only get the capability tests you use. The branch is at: https://github.com/bramstein/treesaver/tree/newdom

Perhaps has.js is a better candidate if it works natively (or has a fork that works natively) with closure compiler.
