### ISSUE TITLE
Replace mustache.js with handlebars.js

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#229]
Handlebars.js can be precompiled and has better support for encoding/escaping values which we need for encoding URL parameters. The syntax should be almost identical so no major syntax changes.

**Comment by fortes** [comment]
I think this is the right thing to do. Not sure we'll use all the features, but compiling with Closure's advanced mode should strip out anything we don't use.

**Comment by bramstein** [comment]
I'm not sure if we can use it with Closure's advanced mode. I just tried using simple optimizations and that seems to work.

**Comment by bramstein** [comment]
I just replaced Mustache.js with Handlebars:

https://github.com/bramstein/treesaver/commit/5157389f0a3ef7c12d7f9ebdd25a785081ff1cc9

I still want to do some additional testing and make those escape functions available to the templates before I close the ticket, but it seems to work fine so far.

**Comment by bramstein** [comment]
This is completed now. Small note for SN: we'll need to use the handlebar helpers for templates that replace variables in attributes or inside URLs. For an example, see the `currentdocument` template in the `template-currentdocument` example.

**Comment by fortes** [comment]
Excellent, thanks!

**Comment by fortes** [comment]
Hm, looks like using Handlebars adds 25K to our final compiled size, which is a lot for not much functionality (brings compiled size to 90K, so it's over 25% of the download size).

Since we're not using all the features, we could see if advanced compilation works better here. If not, we can either fork and remove the parts we don't need, or try to extend mustache.

Other ideas?

**Comment by fortes** [comment]
A quick test for advanced mode drops 6K off of compiled, bringing total to 83K (did not test if it still worked OK though). That means we may have to consider some other strategies here to keep file size down.

**Comment by bramstein** [comment]
I tried it as well, it stops working unless we annotate it ourselves. We can manually shave off a couple of bytes (I've tried), but the bulk of the code is due to the generated lexer and parser, which are necessary. Precompiled templates should make a huge difference once we have a Treesaver compiler, but it will take a while till we get there.

Hacking Mustache to support custom encoding/escaping syntax is the cheaper option with regards to file size.

**Comment by fortes** [comment]
> Hacking Mustache to support custom encoding/escaping syntax is the cheaper option with regards to file size.

Took a look at the autogenerated parts of Handlebars, and I'm inclined to agree with you. Seems like it'd be a little tricky to really make that compilation work well.

Aside from the encoding & escaping, is there anything else we really gain from Handlebars? Precompilation, I guess, but we can't even really use that yet.

Can you take a look at how hard it would be to add encoding/escaping to mustache? I can think of many better ways to add 25k to our download :)

**Comment by bramstein** [comment]
Mustache is back now, with a special encodeURIComponent syntax. Instead of the normal double curly braces syntax you can now also use the double-curly-brace-dollar `{{$my_property$}}` syntax which will run the value through encodeURIComponent. I can add more special escaping syntax if required (I think this one covers our use cases though.)

**Comment by fortes** [comment]
Great! Out of curiosity, why the `$` syntax?

Thinking ahead, we may have need for HTML encoding as well, may be a good idea to come up with a reasonable syntax here for easy documentation. Shame no one else has done something similar, other than Handlebars, I guess. I'm assuming using their syntax is probably too tricky?

The other option I just thought of: In theory, we could just force people to output correctly encoded items in their JSON. Might be harder to document or explain though.

**Comment by fortes** [comment]
Nevermind, I just looked through the source and see why you chose `$`

**Comment by bramstein** [comment]
It was the first character I found that didn't have meaning in Mustache.js. I also tried `@` but it looked a little weird.

Mustache does HTML encoding/escaping by default, or are you talking about something else?

I thought about that option as well, but it gets a little awkward when it comes to using URLs for meta-data and TOC data.

**Comment by fortes** [comment]
I was talking before doing enough research :)  Found the `{{{` option for mustache, which does what we need.

I'm hoping they'll add native support someday to Mustache so we don't maintain a fork. Want to send them a pull request?

**Comment by bramstein** [comment]
I hope they will. I'll need to clean it up a bit and add some unit tests before doing a pull request. Seems my Ruby environment is a bit broken, so I'll tackle that some other day.
