### ISSUE TITLE
Expose API for setting article and app-wide Metadata

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#232]
Need an API that allows developers to manipulate the bindable metadata that exists for Chrome and pages.

Specific scenario involves data that is fetched via timer, and then needs to refresh data displayed within Chrome.

**Comment by bramstein** [comment]
This has been done per SHA: 4fc965488cb3d32fb94b837c8c7113e00c778d44

We should improve the API though. Opening a separate ticket for that.
