### ISSUE TITLE
Support requirements for articles in TOC

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#233]
Add the ability to use `requires` in the TOC articles just like with `Figure`. For example:

``` js
[
  { "url": "one.html" },
  { "url": "two.html", requires: "flash" }
]
```

The second article would not be shown if the browser does not have flash. This is also useful for showing certain articles only when online, etc.

**Comment by bramstein** [comment]
This has been implemented per SHA: f3df05760b73509c6128e0df16a04550f9d39749
