### ISSUE TITLE
Consider using Closure Compiler API service in cases where Closure Compiler does not work

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#248]
Just an idea, may not meet our needs (and would kill building while offline): http://code.google.com/closure/compiler/docs/api-ref.html

**Comment by bramstein** [comment]
I don't think this will work, the API forces you to either URL encode your JavaScript file and put it in a POST parameter with a limit of 200,000 bytes. Assuming we concatenate our code, we're probably above that figure. There is also the `code_url` parameter which has a higher byte size limit, but it forces you to upload your file somewhere publicly accessible.

In either case we still need to resolve the dependencies first.

**Comment by fortes** [comment]
Yeah, we're definitely over the 200K limit. I guess we could plug into some kind of upload service or something, but that's a bit more work.

Closing, we can always reopen if they change how the API service works.
