### ISSUE TITLE
{{url}} binding under #contents breaks in FireFox(6)

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#259]
Everything under #contents in FireFox works properly aside from {{url}}

**Comment by fortes** [comment]
This is related to #257 and #258.

You should be able to use `data-href` as a workaround.

**Comment by bramstein** [comment]
This is now fixed per SHA: ee683faa5c243dc77fbc7847a03cb933360721fe 

See the issues @fortes mentioned for more information.
