### ISSUE TITLE
onlypage doubled on all verticals

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#26]
latest js drop doubled onlypage templates

**Comment by scottkellum** [comment]
isolated this. When you navigate to the root dir of the vertical it creates one page for "/" and another page for "/index.html".
linking straight to "/index.html" solves this for now.

**Comment by fortes** [comment]
The system has no way to know that '/' and '/index.html' are the same page (in some cases, they may not be).

Use rev="contents self" instead of just rev="contents" in order to make this work correctly.

Latest js should support this. Let me know if you run into any issues.
