### ISSUE TITLE
Redesign the meta-data and settings API

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#264]

**Comment by fortes** [comment]
This is definitely needed, and not just for metadata and settings, I think we need to come up with the general API for Treesaver, including (at least):
- Navigation commands: next/prev page/article, nav to specific article, etc
- Metadata / settings
- Online/offline
- Events (incl list of existing)
- Plenty of others

We can do this one at a time though, they will require some thought.

**Comment by andreacampi** [comment]
Bram, can you provide some more context on this ticket? As it stands, it's not actionable.
