### ISSUE TITLE
Firefox & line-height

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#266]
When NOT using a whole number for line-height in FireFox. The line-height gets set to 1px.

For example if the line-height is 1.3em, then FireFox will turn the line-height to 1px.

**Comment by mattguest** [comment]
I found that Firefox seems to work with half numbers as well (1.5, 2.5, etc)

**Comment by andreacampi** [comment]
I cannot reproduce this bug; I will give it some more time and then close it.

**Comment by andreacampi** [comment]
As I wrote I cannot reproduce it; it's also likely that the behavior has been changed by the recent Chrome fixes.
