### ISSUE TITLE
Blurry on Safari

### ISSUE THREAD

**Issue by mrafal** [Treesaver/treesaver#268]
Sometimes the treesaver publication viewed on Safari browser gets very blurry. 

Steps to reproduce:
1. Go to http://demo.nomadeditions.com/real-eats/ on Safari
2. Go to page that includes a lot of text (the problem is less visible on pages with pictures)
3. Change slowly the browser's window width 

At some point the whole page gets blurry.
(just a speculation: perhaps somewhere in the code that calculates layout, x-offset is not rounded?)

Observed on Safari 5.1.1 on Windows Vista and on Ipad. On ipad it is more difficult to reproduce, since you cannot freely change browser window width.

**Comment by scottkellum** [comment]
Have not been able to replicate in current builds. Closing for now.
