### ISSUE TITLE
Safari 3 compatability

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#27]
fails to load pages.

**Comment by fortes** [comment]
Let's cut support for Safari 3 -- just need to find the right feature detection in order to do so.

**Comment by fortes** [comment]
SHA: 705ddc659b9f56222ad032a97889c4453ac4d4e7

Removes support for Safari before version 4 (will get scrolling view). Please confirm when you get a chance (you can use newsdemo)
