### ISSUE TITLE
Export ArticleManager symbols

### ISSUE THREAD

**Issue by andreacampi** [Treesaver/treesaver#271]
Currently treesaver.goToDocumentByURL and friends are only exported if running within an iOS wrapper.
I was wondering, what was the reasoning behind that? Is there any downside I'm not seeing?

I find these useful also in other cases where there is some JavaScript; one example I can think of is embedding within an iframe.

**Comment by bramstein** [comment]
Could you do a pull request for this? There is indeed no good reason for why those are only exported when running inside the  iOS wrapper. Thanks!

**Comment by andreacampi** [comment]
Pull request #285

**Comment by bramstein** [comment]
Thanks a lot!
