### ISSUE TITLE
Menu Functionality

### ISSUE THREAD

**Issue by aliciaduffy** [Treesaver/treesaver#277]
I am using the latest build of Treesaver with the new option for multiple menus, I have adjusted my markup to have the menu class on the parent div, but clicking on any of the links in the active menu closes the menu – without ever going to the links. Am I missing something?

``````
<div class="menu bottom left">
            <button>Menu</button>
            <ul data-ts-template="currentdocument">
            <li class="first"><a  data-href="http://www.facebook.com/sharer.php?u={{$url$}}" target="external">Share on Facebook</a></li>
            <li><a data-href="http://twitter.com/?status={{$url$}}" target="external">Share on Twitter</a></li>
            <li><a href="http://www.website.com" target="external">Visit website</a></li>
          </ul>
</div>```

.menu {
display: inline-block;
position: absolute;
 }

.menu.menu-active ul {
display: block;
}

.menu ul {
padding: 0;
margin: 0;
list-style-type: none;
display: none;
position: absolute;
bottom: 20px;
left: 0px;
}
``````

**Comment by scottkellum** [comment]
Hi Alicia,

I was running into this yesterday. The links only seem to work when they are `target="_blank"`.

I will leave this open because this behavior isn’t ideal. Especially with mailto links that open a new window anyway.

**Comment by bramstein** [comment]
Hi,

Try setting target="_blank" on those anchors and see if that helps.

Bram

On Fri, Feb 10, 2012 at 3:19 PM, Alicia Duffy
reply@reply.github.com
wrote:

**Comment by aliciaduffy** [comment]
fixed! thanks guys :)
