### ISSUE TITLE
variable Array.isArray redefined with type function (Object)

### ISSUE THREAD

**Issue by caraya** [Treesaver/treesaver#287]
When trying to compile from Github source I get the following error. 

Users/carlos/experiment/treesaver/src/lib/array.js:29: ERROR - variable Array.isArray redefined with type function (Object): boolean, original definition at externs.zip//es3.js:764 with type function (*): boolean
  Array.isArray = function(value) {
  ^

/Users/carlos/experiment/treesaver/src/lib/object.js:10: ERROR - variable Object.keys redefined with type function (Object): Array.<string>, original definition at externs.zip//es5.js:164 with type function (Object): (Array.<string>|null)
  Object.keys = function(o) {
  ^

2 error(s), 0 warning(s)

Running on MacOSX 10.7 with Python version 2.7.1

Anything I can do on my end short of upgrading Python?

**Comment by andreacampi** [comment]
Python is not needed when building Treesaver 0.10. Let me know if you still have any problem.
