### ISSUE TITLE
Navigation bug with nested articles

### ISSUE THREAD

**Issue by andreacampi** [Treesaver/treesaver#293]
When loading an article with nested contents, we fail to add its children to the index.

You can see this bug in action in `examples/nested-articles`:
- if you load `examples/nested-articles/section1.html` you will see "Section One" followed by "Section Two"; the articles from "Section One" won't be accessible when navigating with arrows etc;
- if you go back to the TOC and click on a link to an article from that section, it won't be recognized as an internal Treesaver link, so we will reload the whole page, chrome and all. It's pretty subtle and most end users probably won't notice, but it's not nice;
- much worse, if you are reading the publication on an iOS device from the "Home Screen", those articles will be opened in Safari!

**Comment by bramstein** [comment]
Thanks, I've just merged it in.
