### ISSUE TITLE
Firefox 16 beta

### ISSUE THREAD

**Issue by meddijim** [Treesaver/treesaver#300]
My Test Code works on:
IE9 win7
IE10 win8 Beta
FF15 win8 Beta
IPad horizontal and Vertical
and even iPhone

but

Getting a problem with Firefox 16 Beta - individual articles are fine but Toc doesn't build.

[09:15:38.470] TypeError: a.properties.forEach is not a function 
@ .../treesaver-0.9.2.js:74

function Kc(a){var b={},c={},d={};if(a.itemType)b.type=a.itemType;if(a.itemId)b.id=a.itemId;if(G(a,"data-properties")){a.getAttribute("data-properties").split(/\s+/g).forEach(function(e){d[e]=g});b.sa=d}a.properties.forEach(function(e){var f=e.itemValue,h=[];if(f.itemScope)f=Kc(f);h=e.itemProp.split(/\s+/g);h.forEach(function(o){c[o]||(c[o]=[]);c[o].push(f)})});b.properties=c;return b}

**Comment by bramstein** [comment]
It seems Firefox 16 has added the microdata API, which Treesaver implements as well. My guess is that we're not detecting support for it (since until now, no browser had support for it) hence the problem you are seeing.

Is there any chance you can upgrade to a more recent Treesaver release, as newer releases do not use microdata.

**Comment by andreacampi** [comment]
By the way, I am planning a new release in the next few days, once I finish merging the Chrome fixes plus the new Webfonts support.

**Comment by meddijim** [comment]
Bramstein - thanks for the explanation. At least it's not my coding.

What version of treesaver...js should I use and would you kindly post a link.

andreacampi - great to hear that there will be a new version shortly and I am looking forward to the release.

Thanks to both for prompt responses ...

**Comment by bramstein** [comment]
You can download Treesaver 0.9.3 at: https://github.com/bramstein/treesaver/downloads

It might be worth waiting until Andrea releases a new version though, since the above does not include all the recent fixes.

**Comment by andreacampi** [comment]
I can confirm that a recent build works fine on Firefox 16.
Stay tuned for a 0.9.4 release this week.

**Comment by meddijim** [comment]
Great news - I look forward to running the new version

**Comment by wvdongen** [comment]
Hi Andrea, have you released 0.9.4 yet? Can you tell me where I can find the download? Thanks

**Comment by andreacampi** [comment]
Just released it, you can find it at https://github.com/Treesaver/treesaver/downloads
In the end I decided to call it 0.10.0 since it contains backward-incompatible changes.

I still have to update the release notes and review the rest of the documentation, then I'll post to the ml.
In the meantime, let me know how it works for you!

**Comment by wvdongen** [comment]
Thanks! However due to the incompatible changes a simple upgrade doesn’t seem to be possible. I’ll have to wait for the release of the documentation so I can see what needs to be changed in order to get it working.

**Comment by andreacampi** [comment]
Oops, yeah…

Look at https://github.com/Treesaver/treesaver/tree/master/examples if you want to get a head start, you should probably be able to figure it out.
I'll get started very soon, and I'll try to put together a "migration guide". But that's a "best effort" thing, help is very welcome.

**Comment by andreacampi** [comment]
@meddijim @wvdongen I have update most of the wiki page, except for the Walkthrough.

Next I'll see if I can come up with a simple howto guide for upgrading.

**Comment by andreacampi** [comment]
I'm done updating the documentation.

@meddijim let me know how it works for you.

@wvdongen if you have further questions on 0.9.4 vs 0.10 please bring them up on the mailing list.

**Comment by meddijim** [comment]
@andreacampi I have tested 0.10 using JSON on:

Win7 IE9
Win7 FF 17B1
Win8RP IE10RP
Win8RP FF16.0.1
IPAD3 IOS6 Safari

I am pleased to say all works well - thanks
