### ISSUE TITLE
Clipped text

### ISSUE THREAD

**Issue by eugene-brit** [Treesaver/treesaver#309]
Images are loaded via CKeditor. After this I wrap them with "figure" tag. Because of this height is calculated wrong and text of the article is clipped.

**Comment by andreacampi** [comment]
Do you have height attributes on the images and/or min-height attribute on the figure?
Do these agree with the CSS?

Can you point me to an online example, or at least a gist with an extract of the markup and CSS?

**Comment by eugene-brit** [comment]
The img tag always has height and width attributes inserted by CKEditor when inserting the image. In this case there was situation when one part of the image is displayed in one column and second part - in the next column of the reader.
After that I've tryied to wrap this img tag with figure tag. In this case image fit in one column. If it's not fit in the first column, Treesaver moves whole image in the start of the next column. But there was cases when Treesaver calculated height of the column in wrong way and the last one of the column was visible only on half of its height.
Here is the screenshot of this "effect": http://awesomescreenshot.com/06cndftb3

Here is the example of the markup: https://gist.github.com/4136164

PS. Text with images into it is inserted (generated) by CMS.

**Comment by andreacampi** [comment]
From the screenshot the image looks much taller than 161 pixel; I guess it's from a different attempt?

The markup for the figure is wrong, please review the documentation:
- https://github.com/Treesaver/treesaver/wiki/Walkthrough
- https://github.com/Treesaver/treesaver/wiki/Figure

Also, I'm not sure but the <figure> inside a paragraph may spell trouble. You should move it so it's a direct child of the <article>.

This is not a bug with Treesaver; please bring this up on the mailing list and we'll try to help.
