### ISSUE TITLE
When i download from github and opened the file in chrome it is not working

### ISSUE THREAD

**Issue by Sampathmattapalli** [Treesaver/treesaver#320]
Am downloaded all available versions from github even any version not working in chrome & IE but working in Mozilla why it is not working in other browsers, i saw some other website like below those are working fine in all browsers.

http://demo.nomadeditions.com/real-eats/another-roadside-attraction.html
http://savory-demo-newsprint.savory.io/one/articles

**Comment by giorgian** [comment]
Hi,

please have a look at the very first of the [FAQ](https://github.com/Treesaver/treesaver/wiki/FAQ): you'll notice that it clearly says that, since Treesaver uses XHR requests, it won't work with `file:///` paths on most browsers.

You'll have to serve it through a web server.

**Comment by Sampathmattapalli** [comment]
Hi giorgian 

Thank you very much.
