### ISSUE TITLE
1px margin below chrome in iOS

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#35]
The chrome starts 1px above the bottom of a page in iOS (iPhone and iPad tested).

**Comment by scottkellum** [comment]
Looks like the page has been scrolled down too far. hitting the page title moves everything back up and into place.

I assume you move the page down to hide the address bar on the iPhone, maybe making it iPhone specific (not on the iPad) will prevent this.

**Comment by fortes** [comment]
Fixed in SHA: 5c4f16ff7897b9f768e2d79d0c3d5f3e2c287f9b
