### ISSUE TITLE
Constrain dimensions for lightboxes

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#36]
The problem is that image widths 

Widths are based on classes like w1col, w2col, w3col ... w12col. Combine that with a ratio to constrain height as well: "w3col r4x3"

Using data-sizes for measurement has been depreciated to standardize widths across all containers, not just images... can add back in if necessary...

**Comment by fortes** [comment]
I'm not sure how to do this in a generic way for you. I think you should go with data-sizes, since that is automatically assigned to the container in the lightbox.

Otherwise, how is the system to know which classes to set on the container for sizing?

**Comment by scottkellum** [comment]
Makes sense. I will try to figure this out in an elegant way and will close this when I get it figured out.

**Comment by scottkellum** [comment]
fixed by adding lists of dada-sizes to width styles.
