### ISSUE TITLE
Event handling does not work in IE9

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#4]
IE9 doesn't allow an object as an event target, so all use of `handleEvent` fails

**Comment by scottkellum** [comment]
Seems to fail in other versions of IE as well. Was not able to navigate away from the cover in IE8

**Comment by fortes** [comment]
Patch storage and events in order to work with latest IE9 beta. Closed by 283f1bf9752c962e1ece1b6703b0f2bfe85a376d
