### ISSUE TITLE
Flow bug on mobile

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#40]
Getting reports of the infamous flow bug on mobile devices between the first and 2nd pages. Haven't seen it yet, need to replicate and diagnose.

**Comment by fortes** [comment]
Still getting reports?

**Comment by scottkellum** [comment]
It probably has to do with font loading. Most noticeable on iPhone landscape.

**Comment by fortes** [comment]
Anything else coming up here? If not, let's close it (better to track specific issues)

**Comment by scottkellum** [comment]
Closing it.
