### ISSUE TITLE
Support 2-up view on Chrome

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#43]
For more magazine-like layouts, can also help curb template explosion.

**Comment by scottkellum** [comment]
How will this curb template explosion?

I added the class "spread" in my CSS that creates fake spreads when used with the classes "even" and "odd" if you want to integrate that.

**Comment by fortes** [comment]
Netbook could use two iphone templates instead of needing one of its own, etc. Could halve the number of templates
