### ISSUE TITLE
Ability to put close button inside the light-box container

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#45]
Items like close-buttons will need to be positioned relative to the containers. Having the ability to place elements inside the containers will help with this.

Maybe append to contains of the light-box container will work.

**Comment by fortes** [comment]
I'm thinking sizetocontainer flag, like in Grid.

**Comment by scottkellum** [comment]
fixed in CSS.

**Comment by fortes** [comment]
Keeping open to track this to either document or build something in.
