### ISSUE TITLE
Previous/Next page buttons are disabled when loading

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#52]
Previous/Next page buttons are disabled when the previous/next article has not yet been loaded. This can be seen by loading a Treesaver issue in the middle of its contents and quickly navigating forward and backward.

**Comment by fortes** [comment]
I see this happen, but it only stays that way until the TOC has loaded. Should be the correct behavior, no? Since if the TOC is loaded, the user cannot go back.

Or am I not seeing the behavior you're seeing?

**Comment by bramstein** [comment]
I just tried it again, and I think you are correct. The problem is the short moment between pressing the previous/next buttons and loading in the previous or next article. It is probably a good idea to disable the buttons in that moment.
