### ISSUE TITLE
Photo act intro text

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#54]
Text is just missing. All the photos show up.

**Comment by fortes** [comment]
I thought you said this was your template issue?

**Comment by scottkellum** [comment]
It may be, I thought it was scoring the figure out of placement. Before it was just placing the first page at the end but I can't get it to place anywhere now...

**Comment by scottkellum** [comment]
fixed.
.photostory{margin:20px}
changed to
.photostory.grid(margin:20px)
