### ISSUE TITLE
Contents “scrubber” not pulling content 

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#55]
Latest JS in both Real  Eats and Wave Lines.

**Comment by bramstein** [comment]
I had a look at this, and it seems you are using the latest version of the JavaScript. This new version replaces the old syntax for the table of contents, content fields and data-binding in the Chrome. I will update the Wiki with the latest syntax.

**Comment by scottkellum** [comment]
OK, thanks.
noticed page numbers and other things weren't working as well.

**Comment by bramstein** [comment]
See https://github.com/Treesaver/treesaver/wiki/Chrome and https://github.com/Treesaver/treesaver/wiki/Field for the updated syntax. Let me know if you run into any problems.
