### ISSUE TITLE
Templated link binding is whitespace sensitive

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#57]
Works: a data-href="http://twitter.com/?status={{current-url}}" data-bind="current-url:href"

Doesn't work: a data-href="http://twitter.com/?status={{ current-url }}" data-bind="current-url:href"

(note spaces between mustaches and variable name)

**Comment by bramstein** [comment]
Fixed per 16cdea4. Should they also be case-insensitive?

**Comment by fortes** [comment]
Maybe some day, not important right now.
