### ISSUE TITLE
Opera/General: Loading resources

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#62]
I was just looking into why Opera doesn't work, and one of the main issues is the way resources are loaded. Currently, resources are loaded by retrieving a HTML document using XHR. This document is then appended as a child of a detached DIV element. The DIV children of the DIV element are then added to the `treesaver.resources.container_` container. The problem is in how different browsers deal with appending a document to an element. 

Firefox appends all the child elements of `head` and `body` to the DIV. Chrome only appends the child elements of `body`, and (the problem) Opera appends the child elements of `head` and the `body` itself.

Perhaps this piece of code should be rewritten so it doesn't rely on undetermined behaviour.

**Comment by fortes** [comment]
Agreed.

A long time ago, I used to load up the resources file via iframe. That ran into other annoying issues that I can't remember right now (was about a year ago).

Ideas? Off the top of my head we could try to use a regex to extract within the body tag. Can be error prone though.

**Comment by bramstein** [comment]
My first plan was iframes as well, but I guess you already tried that then. I thought a quick fix would be iterating through the elements and if a `body` element is found process its children as usual (instead of ignoring it as it does now.)

**Comment by bramstein** [comment]
FYI: I put in the hack I described earlier a while ago, so things are working in the latest Opera. The Wii browser does not work---it just doesn't load. I don't have any experience debugging that, but perhaps getting Opera 9 to work is a good start.

**Comment by fortes** [comment]
Let's only support recent versions of Opera, say 10.5. We can always loosen up later on, but I don't want to be totally broken on a browser.

Do we have a good capability test for restricting Opera here? That's good enough for me (what I did with Firefox 3 by choosing querySelectorAll).

**Comment by bramstein** [comment]
Is 10.10 and higher also acceptable? I tried and it only fails in 9.64, 10.10 is a capable browser and runs Treesaver fine. I will see if I can come up with a capability test.

By the way, from a brief look, I don't think supporting 9.X (and thus the Wii) is that much work, but we will take that later.

**Comment by bramstein** [comment]
Fixed per SHA: 82ba531753a0cf6b3310dde409fbcaa684f628a1

I also tested on the Wii and it properly falls back on normal HTML pages.

**Comment by fortes** [comment]
Great. Closing.
