### ISSUE TITLE
Support no-page-1, no-page-2, etc Grid flags

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#64]
Having problems with odd grids outscoring page-1 templates with the new JS. Would like it if page-x were forced to show in designated position unless it can't fit. A huge bump to the scoring should hold me off though.

http://treesaver.net/preview/realeats/dryrun/03-tvdinner.html
http://treesaver.net/preview/realeats/dryrun/04-willwork.html

**Comment by fortes** [comment]
How about something like `no-page-1` in order to prevent a template from being a specific page. Would that fix this issue?

**Comment by scottkellum** [comment]
That would do the trick, Will this also work for "no-page-2..."

**Comment by fortes** [comment]
Add no-page-1, etc flags. Closed by 49e7a57b6606054ae7d784a1ee4ab051e1520f04
