### ISSUE TITLE
IE: ArticleManager.currentArticleIndex fails

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#65]
When the initial article URL is compared against entries in the TOC to find the current article index it does not take into account that the browser may have a different URL.

Given a page at:
     http://www.example.org/?something=hello%20world
And TOC microdata like this:
     <a href="" itemprop="url">Some url</a>
This will result in a TOC entry like this (on IE7/8:)
     { url: "http:///www.example.org/" }

This will then later fail when the TOC url is compared against the initial URL (which does have the query part.)

**Comment by fortes** [comment]
Yeah, this is why I had the "self" flag on links for a while -- also happens with '/' and '/index.html' at times.

This is a tricky problem to solve without the content given an indication of canonical URL. Perhaps TS should read in the `<link rel="canonical" />` of the current page? Other ideas?
