### ISSUE TITLE
IE7: Mouse events are only registered on actual content, not columns

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#76]
When clicking the next article to navigate to it: it only works when the actual content is clicked (say a paragraph or an image) and not the column container.

**Comment by fortes** [comment]
There's a similar problem on touch devices as well, will probably have to set a bogus click handler or something similar.

**Comment by bramstein** [comment]
Do you want a click handler on pages, or on a the whole area around a page (i.e. a click on the background surrounding a page triggers events on that page?) You could argue both ways: selecting non-content and non-ui areas makes sense when you don't want to trigger any action but just dismiss a sidebar or menu. On the other hand, people might accidentally select an area that is not content, but where they still expect an event to be triggered. Personally I'm leaning towards the latter (the UI makes it easy to correct an incorrect action.)

**Comment by bramstein** [comment]
Turns out that IE doesn't consider elements with a transparent background as click targets. Adding a white background colour fixes the issue in the functional test. Fixed per SHA: 92152af67b1631a25e576664f55edb02a02c35d5
