### ISSUE TITLE
Test in Windows Phone 7

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#84]
Need to get a test phone or emulator.

**Comment by bramstein** [comment]
Emulator: http://create.msdn.com/en-us/home/getting_started

**Comment by fortes** [comment]
Windows Phone 7 doesn't pass the capability flag. This is by design for now, since that browser is terrible (based on IE7) and doesn't support touch events, making paging really terrible.

Can consider adding support some other time.
