### ISSUE TITLE
IE7: Headers return offsetHeight larger than the actual value

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#86]
The column layout seems slightly wrong in IE7. After investigating this problem it turned out to be a problem with the `offsetHeight` reported by IE7, and treesaver's desire to keep everything aligned to a grid. IE7 will, for example, on a H2 with `line-height: 20px` and `font-size: 20px` return an `offsetHeight` of 23 pixels, while all other browsers return 20 pixels. Interestingly if you measure the visual size of the H2 it comes out at exactly 20 pixels.

Treesaver insists on aligning everything on a line-height based grid, so the above situation will add 17px of margin to the bottom of each H2 element (and likewise any other element that exhibits the same behaviour in IE7.) I'm not sure yet if this is the cause of the column height problems in IE7, or if it is an unrelated problem.

**Comment by fortes** [comment]
We can disable the auto vertical grid (there's a flag a user can set, I use it in the News Demo).

However, this doesn't solve the root problem here: We can't accurately measure the offsetHeight. Is there a workaround for that?

**Comment by bramstein** [comment]
I haven't found one yet. I did some tests in jQuery, and it seems it also returns "23" as the value. I tried all other ways of retrieving the height I could think of, but haven't found anything that returns the correct value.

I put a small test in the Treesaver dropbox shared folder that demonstrates the problem and boils it down to the smallest test case.

**Comment by bramstein** [comment]
I'm fairly convinced this and the column height problem are one and the same. I adjusted the font sizes in the functional/simple test so that the resulting offsetHeight is a multiple of the line-height, and the column height problem disappears.

**Comment by bramstein** [comment]
Interesting. When I set the headers to `display: inline-block` it returns the correct offsetHeight!

**Comment by bramstein** [comment]
Seem triggering `hasLayout` on the measured element fixes the problem. I'll try to turn this into a generic solution.

**Comment by fortes** [comment]
Ah, `hasLayout` -- the fix for all IE bugs. We should have known! :)

**Comment by bramstein** [comment]
Fixed per SHA: 0c678744644a8a6d50b2ca727c8d049d62f0f592

Should have known yes. I had never seen this hasLayout related problem before though.

**Comment by fortes** [comment]
I haven't either, but do remember using the trick when I'm at my wit's end with IE (learned it from some people that wrote the browser)
