### ISSUE TITLE
IE7: Large figures have too much margin top

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#89]
Large figures in IE7 receive too much margin top, resulting in less than than usual above or below the figure.

**Comment by bramstein** [comment]
The column height is calculated incorrectly. I haven't discovered yet why this happens. When setting the height manually the problem is resolved. Seems to be in the code that calculates the top and bottom offset for a column container.

**Comment by fortes** [comment]
Watch out with this code, it's been a source of many bugs. Sizing w/ CSS is tricky, and understanding author intent is non-trivial. Do you have any more details?

**Comment by bramstein** [comment]
Ugh. This is getting nasty. After a lot of trail and error it seems IE7 is not triggering redraws at the right moment. If I add a `el.className = el.className;` statement at the end of `treesaver.dom.addClass` it seems to trigger a redraw and gives a slightly better height calculation. My bet is that there should be another redraw somewhere to fix the height issue completely.

Not sure how or if to continue.

**Comment by fortes** [comment]
Sometimes you can force a re-layout by accessing offsetTop/Height, perhaps we need to access twice? Not sure.

Don't spend too much more time on this though. Just not worth it.

Make sure you wrap these IE7 fixes in SUPPORT_IE and treesaver.capabilities.IS_LEGACY -- that way we can clean them out whenever we cut IE7 support.

**Comment by bramstein** [comment]
This seems to have been fixed in the mean time (I assume one of your changes fixed it.)
