### ISSUE TITLE
IE7/8: Reloading on the TOC tries to load /index.html

### ISSUE THREAD

**Issue by bramstein** [Treesaver/treesaver#90]
Steps to reproduce:
- Load the test/functional/simple example in IE7/8
- Navigate to the first article
- Reload
- Navigate back to the TOC (Note: fragment identifier set to #-/index.html)
- Reload

The browser then tries to load /index.html.

**Comment by fortes** [comment]
IE7 doesn't know how to compute absolute URLs without innerHTML. Closed by 80d839edba974e8a391ac9bfa136f91421efc313
