### ISSUE TITLE
Capability filter rejects 3rd Gen iPod Touch Running iOS4

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#91]
Craig Weber has one. Works fine on iOS4 on iPhones and in simulator. No idea how to debug this without having the actual device.

**Comment by scottkellum** [comment]
Confirmed this bug extends to the 4th gen iPod touch...

**Comment by fortes** [comment]
Properly detect ipod touch, and fix stupid coding mistake that caused null reference error with unrecognized platforms. Closed by 96450b2c08c3d25c97d8364fdeeaa7784960382f
